// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAADpwo516FKXH9aNnT5m05JXz3QEL4lY',
    appId: '1:904304752242:web:b40b0890fc78f492fd34eb',
    messagingSenderId: '904304752242',
    projectId: 'medicare-aec3f',
    authDomain: 'medicare-aec3f.firebaseapp.com',
    storageBucket: 'medicare-aec3f.appspot.com',
    measurementId: 'G-L3X9ZVLYJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL6geEaQv6A_FY0Fc1eA1V93BwcPVY-qg',
    appId: '1:904304752242:android:f1244653a30412bafd34eb',
    messagingSenderId: '904304752242',
    projectId: 'medicare-aec3f',
    storageBucket: 'medicare-aec3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCOewh7P5C1PKrsWCeG4P5qPXlwKjMXC8',
    appId: '1:904304752242:ios:05832e63fe179f71fd34eb',
    messagingSenderId: '904304752242',
    projectId: 'medicare-aec3f',
    storageBucket: 'medicare-aec3f.appspot.com',
    iosBundleId: 'com.example.medicareDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCOewh7P5C1PKrsWCeG4P5qPXlwKjMXC8',
    appId: '1:904304752242:ios:c63ce834bfb4b5c3fd34eb',
    messagingSenderId: '904304752242',
    projectId: 'medicare-aec3f',
    storageBucket: 'medicare-aec3f.appspot.com',
    iosBundleId: 'com.example.medicareDart.RunnerTests',
  );
}
